api_platform:
    mapping:
        paths:
        - '%kernel.project_dir%/config/packages/api_platform/resources.yaml'
    # The list of enabled formats. The first one will be the default.
    formats:
        # Disabled json-ld to avoid coupling on data structures
        #jsonld:
        #    mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']







